home/urls.py
from django.urls import path
from . import views as home_views

app_name = 'passlock'
urlpatterns = [
    path('home/',home_views.LandingView.as_view(),name = 'home'),
   path('account/<int:pk>/',home_views.AccountDetailView.as_view(),name = 'account_detail'),
 	path('account/delete/<int:pk>/',home_views.AccountDeleteView.as_view(),name = 'account_delete'),
 	path('account/edit/<int:pk>/',home_views.AccountEditView.as_view(),name = 'account_edit'),
 	path('account/create/',home_views.AccountCreateView.as_view(),name = 'account_create'),
 	path('user/verify/',home_views.VerifyUserView.as_view(),name = 'verify'),
 	path('account/create-custom-field-for-account/',home_views.CreateCustomFieldForAccountView.as_view(),name = 'add_custom_field_to_account'),
 	path('account/extension/create-custom-field-for-account/',home_views.CreateCustomeFieldForAccountExtensionView.as_view(),name = 'extension_add_custom_field_to_account'),
 	path('account/delete-custom-field-for-account/',home_views.DeleteCustomFieldForAccountView.as_view(),name = 'delete_custom_account'),
]

passlock/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name = 'user/password_reset.html',
        ),
        name = 'password_reset'),
    path(
        'password-reset/confirm/<token>/<uidb64>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html',
        ),
        name = 'password_reset_confirm'),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html',
        ),
        name = 'password_reset_done'),
    path(
        'password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html',
        ),
        name = 'password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views as user_views

app_name = 'user'
urlpatterns = [
    path('user/signin/',LoginView.as_view(template_name = 'user/signin.html'),name = 'signin'),
    path('user/logout/',LogoutView.as_view(),name = 'logout'),
    path('user/register/',user_views.NewUserView.as_view(),name = 'signup'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = 'profile'),
    path('user/profile/edit/',user_views.UserProfileEditView.as_view(),name = 'profile_edit'),
    path('image/url/',user_views.GetProfilePicView.as_view(),name = 'image_url'),
    path('extension/user/verify/',user_views.ExtensionVerifyUserView.as_view(),name = 'extension_verify_user'),
]

home/models.py
# Imports
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
import string



# Create your models here.

class FirstLevelEncryption(models.Model):
    key = models.CharField(max_length = 1)
    value = models.CharField(max_length = 4)
    
    def __str__(self):
        return self.key
    
class FirstLevelDecryption(models.Model):
    key = models.CharField(max_length = 4)
    value = models.CharField(max_length = 1)
    
    def __str__(self):
        return self.key
	
	
class Account(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	account_name = models.CharField(max_length = 100)
	date_created = models.DateTimeField(default = timezone.now)
	date_modified = models.DateTimeField(default = timezone.now)
	
	def get_absolute_url(self):
		return reverse('passlock:account_detail',kwargs = {'pk':self.pk})
	
	
	def __str__(self):
		return f"{self.account_name.capitalize()} Account"
	
class CustomFieldsForAccount(models.Model):
	field_type_choices = (
		('password','Password'),
		('text','Text'),
		('email','Email'),
		('number','Number'),
	)
	account = models.ForeignKey(Account,on_delete=models.CASCADE)
	field_name = models.CharField(max_length = 100)
	field_type = models.CharField(max_length = 100,choices = field_type_choices)
	field_value = models.CharField(max_length = 100)
	
	def save(self):
		if self.field_type.lower() == 'password':
			encryption = Encryption(self.field_value)
			self.field_value = encryption.encrypt()
		super().save()
		
	def decrypt_password(self):
		if self.field_type == 'password':
			decryption = Decryption(self.field_value)
			return decryption.decrypt()
	
	def __str__(self):
		return f"{self.account.account_name}'s > {self.field_name}"
	
class Encryption:
    """ This class contains algorithms that will encrypt a user's password """
    
    def __init__(self,password):
        self.password = password
    
    def level_one_encryption(self):
        """ This is the first level in the enryption process where every single character of the password is replaced with four characters """
        level_one_encryption_data = ''
        # Goes through every character
        for char in self.password:
            encryption_data = get_object_or_404(FirstLevelEncryption,key = char) # Gets the four characters to replace the character
            level_one_encryption_data += encryption_data.value # Create an encrypted data
            
        return level_one_encryption_data
        
    def level_two_encryption(self,password):
        """  This is the second stage of the encryption process where each character is the changed to a different character using an algorithm """
        level_two_encryption_data = ''
        # Get all the printable characters and remove unwanted ones
        modified_string = string.printable.strip()
        # A list with an equal length with the number of printable characters
        virtual_lst = list(range(len(modified_string)))
        # Goes through every index of the printable characters
        for index in range(len(modified_string)):
            # Sends the position of the index forward thrice
            # Insert the new index of the character in the list
            if index - 3 < 0:
                new_index = len(modified_string) + (index - 3)
                virtual_lst[new_index] = modified_string[index]
            else:
                new_index = index - 3
                virtual_lst[new_index] = modified_string[index]
                
        # Goes through every character in the password
        for char in password:
            # Finds its corresponding character to create another encrypted
            # password
            index_in_modified_string = modified_string.find(char)
            level_two_encryption_data += virtual_lst[index_in_modified_string]
            
        return level_two_encryption_data
            
        
    def level_three_encryption(self,password):
        """ This is the third and last level in the encryption stage """
        virtual_lst = list(password) # Makes a list from the password
        virtual_lst.reverse() # Reverses it
        # Form a new password
        level_three_encryption_data = ''.join(virtual_lst) 
        return level_three_encryption_data
    
    def encrypt(self):
        """ This method is responsible for creating a new password by going
            through all the three stages of encryption"""
        level_one = self.level_one_encryption() # Level one
        level_two = self.level_two_encryption(level_one) # Level two
        
        return self.level_three_encryption(level_two) # Level three
        
                
        
class Decryption:
    """ This class contains algorithms that will decrypt a user's password """
    
    def __init__(self,password):
        self.password = password
    
    def level_one_decryption(self):
        """ This method is the first level in the decryption stage """
        virtual_lst = list(self.password) # Makes a list from the password
        virtual_lst.reverse() # Reverses it
        # Formrs a new password
        level_one_decryption_data = ''.join(virtual_lst)
        return level_one_decryption_data
    
    def level_two_decryption(self,password):
        """ This is the second stage in the decryption process where the method changes
            every character to a different character generated by an algorithn"""
        level_two_decryption_data = ''
        # Get all the printable characters and remove unwanted ones
        modified_string = string.printable.strip()
        # A list with the same lenght as the number of printable characters
        virtual_lst = list(range(len(modified_string)))
        # Goes through every index of the printable character 
        for index in range(len(modified_string)):
            # Sends the index back three times
            # Replace new index of the character in the list
            if index + 3 > len(modified_string) - 1:
                new_index = (index + 3) - (len(modified_string))
                virtual_lst[new_index] = modified_string[index]
            else:
                new_index = index + 3
                virtual_lst[new_index] = modified_string[index]
                
        # Goes through every character in the string 
        for char in password:
            # Use the character's index  to find it's corresponding character
            index_in_modified_string = modified_string.find(char)
            # Form a new decrypted word
            level_two_decryption_data += virtual_lst[index_in_modified_string]
        return level_two_decryption_data
        
    def level_three_decryption(self,password):
        """ This is the second stage in the decryption process where the method changes
            every four sets of character to its corresponding character"""
        level_three_decryption_data = ''
         # Goes through every four characters of the password  
        for char in range(0,len(password) + 1,4):
            if char - 4 >= 0:
                key = password[char - 4:char]
                # Gets its corresponding character
                decryption_data = get_object_or_404(FirstLevelDecryption,key = key)
                # Form a decrypted word
                level_three_decryption_data += decryption_data.value
				
        return level_three_decryption_data 
    
    def decrypt(self):
        """ This method goes through all the three levels in decrypting a password """
        level_one = self.level_one_decryption() # Level one
        level_two = self.level_two_decryption(level_one) # Level two
        return self.level_three_decryption(level_two) # Level three

	

home/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from django.http import JsonResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .encryption_decryption import Encryption,Decryption
from .models import Account,CustomFieldsForAccount






# Create your views here.
class LandingView(LoginRequiredMixin,generic.ListView):
    model = Account
    template_name = 'home/index.html'
    context_object_name = 'accounts'
    
    def get_queryset(self,*args,**kwargs):
        queryset = Account.objects.filter(user = self.request.user)
		
        return queryset

class AccountDetailView(LoginRequiredMixin,generic.DetailView):
	model = Account
	

class AccountCreateView(generic.View):
	template_name = 'home/account_form.html'
	
	@method_decorator(login_required)
	def dispatch(self,request,*args,**kwargs):
		context = {}
		if request.method == 'POST':
			account_name = request.POST.get('account_name',None)
			user = request.user
			accounts = [account[2] for account in user.account_set.values_list()]
			if account_name not in accounts:
				account = Account(user = user,account_name = account_name)
				account.save()
			
				return HttpResponseRedirect(reverse('passlock:account_edit',kwargs = {'pk':account.pk}))
			messages.error(request,'There account you are trying to create already exists')
			context['acc'] = account_name
			
		return render(request,self.template_name,context)
	

class AccountEditView(generic.View):
	template_name = 'home/account_form.html'
	
	@method_decorator(login_required)
	def dispatch(self,request,*args,**kwargs):
		account_id = int(self.kwargs.get('pk'))
		account = get_object_or_404(Account,id = account_id)
		context = {'object':account}
		if request.method == 'POST':
			account_name = request.POST.get('account_name')
			account.account_name = account_name
			account.date_modified = timezone.now()
			account.save()
			# Get the values in the custom fields
			custom_account_data = [ value for key,value in request.POST.items() if key.startswith('custom_field')]
			# Modify and save the values in the custom fields
			for num,custom in enumerate(account.customfieldsforaccount_set.all()):
				custom.field_value = custom_account_data[num]
				custom.save()
			custom = [c.field_value for c in account.customfieldsforaccount_set.all()]
			# Redirect to the detail page
			return HttpResponseRedirect(reverse('passlock:account_detail',kwargs = {'pk':account.pk}))
			
		return render(request,self.template_name,context)
	
	
	
class AccountDeleteView(generic.View):
	""" This class deletes a default account """
	def dispatch(self,request,*args,**kwargs):
		account_id = self.kwargs.get('pk')
		account = get_object_or_404(Account,id = account_id)
		account.delete()
		
		return HttpResponseRedirect(reverse('passlock:home'))
	
	
	
class VerifyUserView(generic.View):
	""" This verfies an existing user before he or she edits an account """
	def get(self,request):
		password = request.GET.get('password',None)
		username = request.user.username
		authenticate_user = authenticate(username = username,password = password)
		data = {}
		
		data['user_status'] = True if authenticate_user else False
		return JsonResponse(data)

class CreateCustomFieldForAccountView(generic.View):
	""" This class creates a new custom field for a default account """
	
	def get(self,request,*args,**kwargs):
		field_name = request.GET.get("name",None)
		field_type = request.GET.get("type",None)
		encrypted_field_value = request.GET.get("value",None)
		# Get the encrypted field value
		values = encrypted_field_value.split('-')[0]
		keys = encrypted_field_value.split('-')[1]
		field_value = ""
		count = 0
		# Decrypt it
		for i in keys:
			if count < len(values):
				field_value += values[count]
				count += int(i) + 1
			
		account_id = int(request.GET.get("accountId",None))
		account = get_object_or_404(Account,id = account_id)
		custom = CustomFieldsForAccount(
			account = account,
			field_name = field_name.capitalize(),
			field_type = field_type,
			field_value = field_value,
		)
		custom.save()
		
		data = {
			'custom_account_id': custom.id,
		}
		return JsonResponse(data)
	
class CreateCustomeFieldForAccountExtensionView(generic.View):
	""" This class saves customs fields to an account when a user saves an account using the app's extension """
	def get(self,request,*args,**kwargs):
		username = request.GET.get('username',None)
		account_name = request.GET.get('accountName',None)
		field_name = request.GET.get('fieldName',None)
		field_type = request.GET.get('fieldType',None)
		encrypted_field_value = request.GET.get('fieldValue',None)
		# Get the encrypted field value
		values = encrypted_field_value.split('-')[0]
		keys = encrypted_field_value.split('-')[1]
		field_value = ""
		count = 0
		# Decrypt it
		for i in keys:
			if count < len(values):
				field_value += values[count]
				count += int(i) + 1
		# Get the user
		user = User.objects.get(username = username)
		# Get the user's accounts
		all_accounts = user.account_set.values_list('account_name')
		# Filter the user's account
		all_accounts = [x[0] for x in all_accounts]
		if not account_name in all_accounts:
			account = Account(account_name = account_name.capitalize(),user = user)
			account.save()
		account_id = user.account_set.get(account_name = account_name).id
		account = get_object_or_404(Account,id = account_id)
		custom = CustomFieldsForAccount(
			account = account,
			field_name = field_name.capitalize(),
			field_type = field_type,
			field_value = field_value
		)
		custom.save()
		data = {}
		
		return JsonResponse(data)
	
class DeleteCustomFieldForAccountView(generic.View):
	""" This class removes a custom field from a default account """
	def get(self,request,*args,**kwargs):
		# Use the id of the custom account to find the custom account
		custom_account_id = int(request.GET.get('customAccountId',None))
		custom_account = get_object_or_404(CustomFieldsForAccount,id = custom_account_id)
		# Delete if from the database
		custom_account.delete()
		data = {}
		
		return JsonResponse(data)

home/templates/home/account_form.html
{% extends 'home/base.html' %}


{% block head %}
	<title>Edit {{object.account_name}}</title>
{% endblock %}
{% block content %}
	<div class="container" style="margin-top:80px">
		<div id="verification-container" style="max-width:400px;margin:auto;display:none;">
			<p class="text-info">You need to be verified as the actual user before you can edit the account.</p>
			<div class="form-group">
				<label for="password">Password:</label>
				<input id="password" type="password" class = 'form-control' />
			</div>
			<button id="verify" type="button" class="btn btn-primary btn-block">Verify</button>
		</div>
		<form method="post" action="." style="max-width:450px;margin:auto;opacity:1;" class = 'mt-5 mb-5'>
			{% csrf_token %}
			<div class="form-group">
				<label for="{{ form.account_name.id_of_label }}">Account Name</label>
				<input required type="text" name="account_name" id = '{{ form.account_name.id_for_label }}' value="{% if object %}{{ object.account_name }}{% else %}{{acc}}{% endif %}" class="form-control">
				{% if messages %}
					{% for message in messages %}
						<p class = 'text-danger small'>{{ message }}</p>
					{% endfor %}
				{% endif %}
			</div>
			{% if object %}
				<div class="custom">
					<!-- Check for custom fields for the account -->
					{% if object.customfieldsforaccount_set.all %}
						{% for custom_account in object.customfieldsforaccount_set.all %}
							<div class="form-group" id = "{{custom_account.id}}">
								<label for="id_custom_field{{forloop.counter}}">{{object.account_name}} {{ custom_account.field_name }}</label>
								{% if custom_account.field_type.lower == 'password' %}
									<div class="input-group">
										<input type="{{custom_account.field_type}}" name="custom_field{{forloop.counter}}" id = 'id_custom_field{{forloop.counter}}' value="{{ custom_account.decrypt_password }}" class="form-control">
										<div class="input-group-append">
											<button type="button" class=" show-or-hide btn btn-outline-secondary">Show</button>
										</div>
									</div>
								{% else %}
									<input type="{{custom_account.field_type}}" name="custom_field{{forloop.counter}}" id = 'id_custom_field{{forloop.counter}}' value="{{ custom_account.field_value }}" class="form-control">
								{% endif %}
							</div>
						{% endfor %}
					{% endif %}
				</div>
				<hr style = 'margin:auto;width:100%;'/>
				<div class="btn-group mb-4 mt-1" style="width:100%">
					<button data-toggle = 'modal' data-target = '#addModal' type="button" class="btn btn-sm btn-dark">Add Field</button>
					<button id = 'remove' type="button" class="btn btn-sm btn-danger">Remove Field</button>
				</div>
			{% endif %}
			{% if not object %}
				<button type="submit" class="btn btn-primary btn-block">Create Account</button>
			{% else %}
				<button type="submit" class="btn btn-primary btn-block">Save Changes</button>
			{% endif %}
		</form>
		
		<!--Modal For Adding A New Field-->
		<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="addModalLabel">
							Add New Field
						</h5>
						<button class="close" type="button" data-dismiss='modal' aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="form-group">
							<label for="id_field_name">Field Name</label>
							<input required id="id_field_name" type="text" placeholder="E.g. Phone Number" class="form-control">
							<p id="double-custom-field" class="text-danger small"></p>
						</div>
						<div class="form-group">
							<label for="id_field_type">Field Type</label>
							<select class="form-control" name="field-type" id="id_field_type">
								<option value="text">Text</option>
								<option value="email">Email</option>
								<option value="password">Password</option>
								<option selected value="number">Number</option>
							</select>
						</div>
						<div class="form-group">
							<label for="id_field_value">Field Value</label><br/>
							<span id="error" class="small text-danger"></span>
							<input type="text" class="form-control" id="id_field_value" required placeholder="E.g. +233271234567">
							<span id="help" class="small text-info">Enter a valid number</span>
						</div>
					</div>
					<div class="modal-footer">
						<button class="btn btn-secondary btn-sm" type="button" data-dismiss='modal'>Cancel</button>
						<button class="btn btn-danger btn-sm" type="button" id="add-field" >Add</button>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block javascript %}
	<script>
		// A function that verifies a user before editing an account
		let verifyUser = () => {
			$("form").slideUp('fast'); // Remove the form
			$('#verify').click(function(){
				let password = $('#password').val();
				$.ajax({
					url: "{% url 'passlock:verify' %}",
					data: {
						'password':password,
					},
					dataType: 'json',
					success: function(data){
						if(data['user_status']){
							$('#password').attr('class','form-control border-success');
							$('#verify').attr('class','btn btn-success btn-block');
							$('#verify').text('Verified');
							$('#verification-container').slideUp('slow',function(){
								// Remove the verification button to display the form
								$(this).remove();
								$('form').slideDown('slow');
								$('form').css('opacity','1');
							})
						}
						else{
							$('#password').attr('class','form-control border-danger');
						}
					},
				})
			})
		}
		//verifyUser() //Invoke function
		
		// A function that changes the input type based on what the user chooses when forming a custom field
		let changeInputType = () => {
			$('#id_field_type').click(function(){
				let inputType = $(this).val();
				$('#id_field_value').attr('type',inputType)
				$('#help').text(`Enter a valid ${inputType}`);
				$('#error').text("");
			})
		}
		changeInputType(); // Invoke the function
		
		
		// A function that add or deletes custom fields to an account
		let createOrDeleteCustomFields =  () => {
			// Regex for email and number
			let emailRegex = /^[a-zA-Z\d]+@[a-z]+\.(com|org)(\.[a-z]+)?$/;
			let numberRegex = /^\d+$/;
			
			// A function that encrypts any string before making an ajax request
		let encryptBeforeRequest = (string) => {
			let encWord = "";
			let countAdditions = "";
			let ciphers = "r+emip^sudo2lorsi%}tamet,c8on=se@cte3tu?raisc$ing_6elit.Ma0u)s&1aliq7u!et[5male9ad#afeugiat.4Cu*b(itur";
			for(let word of string){
				let encLetter = word;
				let additions = Number(String(Math.random() * 10).split('.')[0]);
				for(let i = 0;i < additions;i++){
					let pos = Number(String(Math.random() * 100).split('.')[0]);
					encLetter += ciphers[pos];
				}
				countAdditions += additions;
				encWord += encLetter;
			}
			encWord += `-${countAdditions}`;
//			console.log(encWord)
			return encWord;
		}
			
			// A function that makes an ajax response in order to add a custom field to a default account
			let ajaxRequestForCustomFields = (name,type,value,accountId) => {
				$.ajax({
					url: "{% url 'passlock:add_custom_field_to_account' %}",
					data: {
						name,
						type,
						'value': encryptBeforeRequest(value),
						accountId,
					},
					dataType: 'json',
					success: function(data){
						$('form div.form-group').last().attr('id',data['custom_account_id'])
					},
				})
			}
			// Create button
			$("#add-field").click(function(){
				let fieldName = $('#id_field_name').val();
				let fieldType = $('#id_field_type').val();
				let fieldValue = $('#id_field_value').val();
				let customFields = [];
				let accountName = $('form div.form-group input').eq(0).val();
				$(this).removeAttr('data-dismiss');
				// Get all the labels in the form
				$('form div.form-group').each(function(){
					if($(this).find('label').text().startsWith(accountName)){
						customFields.push($(this).find('label').text().split(' ')[1].trim())
					}
				})
				if(fieldName && fieldValue){
					if((fieldType === 'email' && emailRegex.test(fieldValue) || fieldType === 'number' && numberRegex.test(fieldValue) || fieldType === 'text' || fieldType === 'password') && !customFields.includes(fieldName) ){
						let formGroupCount = $('form div.form-group');
						if(fieldType !== 'password'){
							$('.custom').append(
								`<div class="form-group">
									<label for="id_${fieldName}">{{object.account_name}} ${capitalizeString(fieldName)}</label>
									<input type="${fieldType}" name="custom_field${formGroupCount.length}" id = 'id_${fieldName}' value="${fieldValue}" class="form-control">
								</div>`
							);
						}
						else{
							$('.custom').append(
								`<div class="form-group">
									<label for="id_${fieldName}">{{object.account_name}} ${capitalizeString(fieldName)}</label>
									<div class="input-group">
										<input type="password" name="custom_field${formGroupCount.length}"  id = 'id_${fieldName}' value="${fieldValue}" class="form-control"/>
										<div class="input-group-append">
											<button type="button" class=" show-or-hide btn btn-outline-secondary">Show</button>
										</div>
									</div>
								</div>`
							);
							$('.show-or-hide').last().click(function(){
								if($(this).text() === 'Show'){
									$(this).parent().parent().find('input[type = "password"]').attr('type','text');
									$(this).text('Hide');
								}
								else{
									$(this).parent().parent().find('input[type = "text"]').attr('type','password');
									$(this).text('Show')
								}
							})
						}
						// Clear the values
						$('#id_field_name').val('');
						$('#id_field_type').val('number');
						$('#id_field_value').val('');
						ajaxRequestForCustomFields(fieldName,fieldType,fieldValue,{{object.id}})
						$(this).attr('data-dismiss','modal');
						$('#help').text(`Enter a valid number`);
						$('#error').text('');
						$('#double-custom-field').text('');
					}
					else{
						$('#help').text(`Enter a valid ${fieldType}`);
						// Checks if the custom field already exists
						if(customFields.includes(fieldName)){
							$('#double-custom-field').text('The custom field you are trying to add already exist for this account.');
						}
						else{
							$('#error').text(`Invalid ${fieldType}`);
						}
					}
							 
				}
			})
			
			// Delete button
			$("#remove").click(function(){
				let totalFormFields = $("form div.form-group").length;
				if(totalFormFields > 1){
					$('form div.form-group').last().slideUp(function(){
						let customAccountId = $(this).attr('id');
						$(this).remove();
						$.ajax({
							url: "{% url 'passlock:delete_custom_account' %}",
							data: {
								customAccountId,
							},
							dataType: 'json',
						})
					}
				)
			}
		})
		}
		createOrDeleteCustomFields() //Invoke function 
		
		// A function that shows or hides a password
		let showOrHide = () => {
			$('.show-or-hide').click(function(){
				if($(this).text() === 'Show'){
					$(this).parent().parent().find('input[type = "password"]').attr('type','text');
					$(this).text('Hide');
				}
				else{
					$(this).parent().parent().find('input[type = "text"]').attr('type','password');
					$(this).text('Show')
				}
			})
		}
		showOrHide() // Invoke function
		
		// A function that capitalizes a word
		let capitalizeString = (word) => {
			return `${word[0].toUpperCase()}${word.substr(1)}`;
		}
		
	</script>
{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{%  static 'home/bootstrap.min.css' %}"/>
    <style>
		#avatar{
			width:35px;
			height:35px;
			position:absolute;
			top:0px;
			border-radius:5px;
			border: 1.5px solid rgba(255,255,255,.5);
			background:rgba(255,255,255,.5);
			padding:2px;
		}
	</style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark ">
          <a class="navbar-brand" href="{% url 'passlock:home' %}">Passlock</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'passlock:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'passlock:account_create' %}">+ Add Account</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="position:relative;" href="{% url 'user:profile' %}">
                	<img id="avatar" src="{{ user.profilepic.profile.url }}" alt=""><span style="margin-left:40px;">Hi {{ user.username }}</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}">
                	Logout
                </a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'home/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'home\bootstrap.bundle.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>