home/urls.py
from django.urls import path
from . import views as home_views

app_name = 'passlock'
urlpatterns = [
    path('home/',home_views.LandingView.as_view(),name = 'home'),
   path('account/<int:pk>/',home_views.AccountDetailView.as_view(),name = 'account_detail'),
 	path('account/delete/<int:pk>/',home_views.AccountDeleteView.as_view(),name = 'account_delete'),
 	path('account/edit/<int:pk>/',home_views.AccountEditView.as_view(),name = 'account_edit'),
 	path('account/create/',home_views.AccountCreateView.as_view(),name = 'account_create'),
 	path('user/verify/',home_views.VerifyUserView.as_view(),name = 'verify'),
 	path('account/create-custom-field-for-account/',home_views.CreateCustomFieldForAccountView.as_view(),name = 'add_custom_field_to_account'),
 	path('account/extension/create-custom-field-for-account/',home_views.CreateCustomeFieldForAccountExtensionView.as_view(),name = 'extension_add_custom_field_to_account'),
 	path('account/delete-custom-field-for-account/',home_views.DeleteCustomFieldForAccountView.as_view(),name = 'delete_custom_account'),
]

passlock/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name = 'user/password_reset.html',
        ),
        name = 'password_reset'),
    path(
        'password-reset/confirm/<token>/<uidb64>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'user/password_reset_confirm.html',
        ),
        name = 'password_reset_confirm'),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'user/password_reset_done.html',
        ),
        name = 'password_reset_done'),
    path(
        'password-reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'user/password_reset_complete.html',
        ),
        name = 'password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views as user_views

app_name = 'user'
urlpatterns = [
    path('user/signin/',LoginView.as_view(template_name = 'user/signin.html'),name = 'signin'),
    path('user/logout/',LogoutView.as_view(),name = 'logout'),
    path('user/register/',user_views.NewUserView.as_view(),name = 'signup'),
    path('user/profile/',user_views.UserProfileView.as_view(),name = 'profile'),
    path('user/profile/edit/',user_views.UserProfileEditView.as_view(),name = 'profile_edit'),
    path('image/url/',user_views.GetProfilePicView.as_view(),name = 'image_url'),
    path('extension/user/verify/',user_views.ExtensionVerifyUserView.as_view(),name = 'extension_verify_user'),
]

home/models.py
# Imports
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
import string



# Create your models here.

class FirstLevelEncryption(models.Model):
    key = models.CharField(max_length = 1)
    value = models.CharField(max_length = 4)
    
    def __str__(self):
        return self.key
    
class FirstLevelDecryption(models.Model):
    key = models.CharField(max_length = 4)
    value = models.CharField(max_length = 1)
    
    def __str__(self):
        return self.key
	
	
class Account(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	account_name = models.CharField(max_length = 100)
	date_created = models.DateTimeField(default = timezone.now)
	date_modified = models.DateTimeField(default = timezone.now)
	
	def get_absolute_url(self):
		return reverse('passlock:account_detail',kwargs = {'pk':self.pk})
	
	
	def __str__(self):
		return f"{self.account_name.capitalize()} Account"
	
class CustomFieldsForAccount(models.Model):
	field_type_choices = (
		('password','Password'),
		('text','Text'),
		('email','Email'),
		('number','Number'),
	)
	account = models.ForeignKey(Account,on_delete=models.CASCADE)
	field_name = models.CharField(max_length = 100)
	field_type = models.CharField(max_length = 100,choices = field_type_choices)
	field_value = models.CharField(max_length = 100)
	
	def save(self):
		if self.field_type.lower() == 'password':
			encryption = Encryption(self.field_value)
			self.field_value = encryption.encrypt()
		super().save()
		
	def decrypt_password(self):
		if self.field_type == 'password':
			decryption = Decryption(self.field_value)
			return decryption.decrypt()
	
	def __str__(self):
		return f"{self.account.account_name}'s > {self.field_name}"
	
class Encryption:
    """ This class contains algorithms that will encrypt a user's password """
    
    def __init__(self,password):
        self.password = password
    
    def level_one_encryption(self):
        """ This is the first level in the enryption process where every single character of the password is replaced with four characters """
        level_one_encryption_data = ''
        # Goes through every character
        for char in self.password:
            encryption_data = get_object_or_404(FirstLevelEncryption,key = char) # Gets the four characters to replace the character
            level_one_encryption_data += encryption_data.value # Create an encrypted data
            
        return level_one_encryption_data
        
    def level_two_encryption(self,password):
        """  This is the second stage of the encryption process where each character is the changed to a different character using an algorithm """
        level_two_encryption_data = ''
        # Get all the printable characters and remove unwanted ones
        modified_string = string.printable.strip()
        # A list with an equal length with the number of printable characters
        virtual_lst = list(range(len(modified_string)))
        # Goes through every index of the printable characters
        for index in range(len(modified_string)):
            # Sends the position of the index forward thrice
            # Insert the new index of the character in the list
            if index - 3 < 0:
                new_index = len(modified_string) + (index - 3)
                virtual_lst[new_index] = modified_string[index]
            else:
                new_index = index - 3
                virtual_lst[new_index] = modified_string[index]
                
        # Goes through every character in the password
        for char in password:
            # Finds its corresponding character to create another encrypted
            # password
            index_in_modified_string = modified_string.find(char)
            level_two_encryption_data += virtual_lst[index_in_modified_string]
            
        return level_two_encryption_data
            
        
    def level_three_encryption(self,password):
        """ This is the third and last level in the encryption stage """
        virtual_lst = list(password) # Makes a list from the password
        virtual_lst.reverse() # Reverses it
        # Form a new password
        level_three_encryption_data = ''.join(virtual_lst) 
        return level_three_encryption_data
    
    def encrypt(self):
        """ This method is responsible for creating a new password by going
            through all the three stages of encryption"""
        level_one = self.level_one_encryption() # Level one
        level_two = self.level_two_encryption(level_one) # Level two
        
        return self.level_three_encryption(level_two) # Level three
        
                
        
class Decryption:
    """ This class contains algorithms that will decrypt a user's password """
    
    def __init__(self,password):
        self.password = password
    
    def level_one_decryption(self):
        """ This method is the first level in the decryption stage """
        virtual_lst = list(self.password) # Makes a list from the password
        virtual_lst.reverse() # Reverses it
        # Formrs a new password
        level_one_decryption_data = ''.join(virtual_lst)
        return level_one_decryption_data
    
    def level_two_decryption(self,password):
        """ This is the second stage in the decryption process where the method changes
            every character to a different character generated by an algorithn"""
        level_two_decryption_data = ''
        # Get all the printable characters and remove unwanted ones
        modified_string = string.printable.strip()
        # A list with the same lenght as the number of printable characters
        virtual_lst = list(range(len(modified_string)))
        # Goes through every index of the printable character 
        for index in range(len(modified_string)):
            # Sends the index back three times
            # Replace new index of the character in the list
            if index + 3 > len(modified_string) - 1:
                new_index = (index + 3) - (len(modified_string))
                virtual_lst[new_index] = modified_string[index]
            else:
                new_index = index + 3
                virtual_lst[new_index] = modified_string[index]
                
        # Goes through every character in the string 
        for char in password:
            # Use the character's index  to find it's corresponding character
            index_in_modified_string = modified_string.find(char)
            # Form a new decrypted word
            level_two_decryption_data += virtual_lst[index_in_modified_string]
        return level_two_decryption_data
        
    def level_three_decryption(self,password):
        """ This is the second stage in the decryption process where the method changes
            every four sets of character to its corresponding character"""
        level_three_decryption_data = ''
         # Goes through every four characters of the password  
        for char in range(0,len(password) + 1,4):
            if char - 4 >= 0:
                key = password[char - 4:char]
                # Gets its corresponding character
                decryption_data = get_object_or_404(FirstLevelDecryption,key = key)
                # Form a decrypted word
                level_three_decryption_data += decryption_data.value
				
        return level_three_decryption_data 
    
    def decrypt(self):
        """ This method goes through all the three levels in decrypting a password """
        level_one = self.level_one_decryption() # Level one
        level_two = self.level_two_decryption(level_one) # Level two
        return self.level_three_decryption(level_two) # Level three

	

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.


class ProfilePic(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    profile = models.ImageField(default = 'default_user.png',upload_to = 'profile_pics')
    
    def __str__(self):
        return f"{self.user.username}'s profile pic"
    
    def save(self):
        super().save()
        img = Image.open(self.profile.path)
        if img.height > 200 or img.width > 200:
            output_size  =(200,200)
            img.thumbnail(output_size)
            img.save(self.profile.path)

user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import ProfilePic
from django import forms

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        widgets = {
            'email' : forms.TextInput(attrs = {
                'class':'form-control',
                'required':'true',
                'type':'email',
            }),
            'password' : forms.TextInput(attrs = {
                'class':'form-control',
                'required':'true',
                'type':'password',
            }),
            'username' : forms.TextInput(attrs = {
                'class':'form-control',
                'required':'true',
                'type':'text',
            }),
        }
		
class UserProfileEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name','last_name','username','email']
		
		widgets = {
			'username':forms.TextInput(attrs = {
				'class':'form-control',
				'placeholder':'Username',
			}),
			'email':forms.EmailInput(attrs = {
				'class':'form-control',
				'placeholder':'Email',
			}),
			'first_name':forms.TextInput(attrs = {
				'class':'form-control',
				'placeholder':'First Name',
			}),
			'last_name':forms.TextInput(attrs = {
				'class':'form-control',
				'placeholder':'Last Name',
			}),
		}

class ProfilePicEditForm(forms.ModelForm):
	class Meta:
		model = ProfilePic
		fields = ['profile']
		widgets = {
			'profile': forms.FileInput(attrs = {
				'class':'custom-file-input',
			})
		}
		required  = {
			'profile':False,
		}

user/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect,JsonResponse
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import NewUserForm,UserProfileEditForm,ProfilePicEditForm
from .models import ProfilePic

# Create your views here.

class NewUserView(View):
    form_class = NewUserForm
    template_name = 'user/signup.html'
    
    def get(self,request,*args,**kwargs):
        form = self.form_class()
        context = {
            'form':form,
        }
        return render(request,self.template_name,context)
    
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        context = {
            'form':form,
        }
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            user = get_object_or_404(User,username = username)
            pp = ProfilePic(user = user)
            pp.save()
            messages.success(request,f"Welcome {username}")
            return HttpResponseRedirect(reverse('passlock:home'))
        return render(request,self.template_name,context)
    
    
class GetProfilePicView(View):
    def get(self,request):
        username = request.GET.get('username',None);
        data = {}
        try:
            user = User.objects.get(username = username)
            pp = user.profilepic
            data['image_url'] = pp.profile.url
        except User.DoesNotExist:
            data['image_url'] = None
        
        return JsonResponse(data)
        
class UserProfileView(View):
	template_name = 'user/profile.html'
	
	@method_decorator(login_required)
	def dispatch(self,request,*args,**kwargs):
		return render(request,self.template_name)
	
	
class UserProfileEditView(LoginRequiredMixin,View):
	template_name = 'user/profile_edit.html'
	form_class1 = UserProfileEditForm
	form_class2 = ProfilePicEditForm
	
	def get(self,*args,**kwargs):
		form1 = self.form_class1(instance = self.request.user)
		form2 = self.form_class2(instance = self.request.user.profilepic)
		context = {
			'u_form':form1,
			'p_form':form2,
		}
		return render(self.request,self.template_name,context)
	
	def post(self,*args,**kwargs):
		form1 = self.form_class1(self.request.POST,instance = self.request.user)
		form2 = self.form_class2(self.request.POST,self.request.FILES,instance = self.request.user.profilepic)
		context = {
			'u_form':form1,
			'p_form':form2,
		}
		
		if form1.is_valid() and form2.is_valid():
			form1.save()
			form2.save()
			return HttpResponseRedirect(reverse('user:profile'))

		return render(self.request,self.template_name,context)
	
	
class ExtensionVerifyUserView(View):
	def get(self,request,*args,**kwargs):
		username = request.GET.get('username')
		password = request.GET.get('password')
		print(username)
		print(password)
		data = {}
		user = authenticate(username = username,password = password)
		if user:
			data['status'] = True
			data['first_name'] = user.first_name
			data['last_name'] = user.last_name
			data['number_of_accounts'] = user.account_set.count()
			data['img_url'] = user.profilepic.profile.url
		else:
			data['status'] = False
		
		return JsonResponse(data)

user/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{%  static 'home/bootstrap.min.css' %}"/>
    <style>
          body{
            margin:auto;
			  overflow:hidden;
        }
        
        #background{
            background-image:url("{% static '\user\images\background.jpg' %}");
            width:100%;
            height:100%;
/*            background-attachment:fixed;*/
            background-size:cover;
			background-repeat:repeat;
            background-position:center;
            position:absolute;
            filter:blur(2px);
			overflow:hidden;
            top:0px;
            z-index:0;
            margin:auto;
            
        }
        form{
            padding:20px 15px 5px 15px;
            background:rgba(255,255,255,0.8);
            border-radius:5px;
        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div id="background"></div>
    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'home/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'home\bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

user/templates/user/password_reset.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Password Reset</title>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:2;">
        <form action="." method="post" style="max-width:400px;margin:80px auto auto auto;">
           {% csrf_token %}
            <div class="form-group">
                {{form.email.label_tag}}
                {{form.email}}
            </div>
            <button class="btn btn-dark btn-block">Request Password Reset</button>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $('#id_email').attr('class','form-control');
    </script>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Password Reset</title>
    <style>
        p{
            background:rgba(255,255,255,.7);
            padding:20px;
            max-width:400px;
            margin:auto;
            margin-top:80px;
            border-radius:5px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:2;">
        <p class="text-center lead">
            Your password has been successfully resetted.
            <a href="{% url 'user:signin' %}" class="btn btn-block btn-dark">Sign In</a>
        </p>
    </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Password Reset</title>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:2;">
        <form action="." method="post" style="max-width:400px;margin:80px auto auto auto;">
           {% csrf_token %}
            <div class="form-group">
                {{form.new_password1.label_tag}}
                {{form.new_password1}}
                <p class="text-info small mt-1">Password should be at least 8 characters long.</p>
            </div>
            <div class="form-group">
                {{form.new_password2.label_tag}}
                {{form.new_password2}}
                <p class="text-info small mt-1">Password should be the same as the password entered above.</p>
            </div>
            <button class="btn btn-dark btn-block">Reset Password</button>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $('#id_new_password1').attr('class','form-control');
        $('#id_new_password2').attr('class','form-control');
    </script>
{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'user/base.html' %}


{% block head %}
    <title>Password Reset</title>
    <style>
        p{
            background:rgba(255,255,255,.7);
            padding:20px;
            max-width:400px;
            margin:auto;
            margin-top:80px;
            border-radius:5px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:2;">
        <p class="text-center lead">An verification token has been sent to your email account..</p>
    </div>
{% endblock %}

user/templates/user/profile.html
{% extends 'home/base.html' %}


{% block head %}
	<title>{{ user.username }} Profile</title>
	<style>
		.card-body img{
			border-radius:50%;
			border:4px solid rgba(0,0,0,.3);
			max-height:160px;
			max-width:160px;
		}
		.row:nth-child(1) .col:nth-child(2){
			line-height:200px;
		}
	</style>
{% endblock %}
{% block content %}
	<div class="container" style="margin-top:80px">
		<div class="card" style="margin:auto;max-width:500px;">
			<div class="card-header bg-secondary">
				<p style="margin:auto;" class = 'text-light text-center'>{{ user.username }}'s Profile</p>
			</div>
			<div class="card-body">
				<div class="row no-gutters">
					<div class="col-sm-5 text-center">
						<img src="{{ user.profilepic.profile.url }}" alt="Avatar">
					</div>
					<div class="col-sm-7 text-sm-left text-center">
						<p class="mt-sm-0 mt-2" >First Name: <span class="text-info">{{ user.first_name }}</span></p>
						<p class="">Last Name: <span class="text-info">{{ user.last_name }}</span></p>
						<p class="">Username: <span class="text-info">{{ user.username }}</span></p>
						<p class="">Email: <span class="text-info">{{ user.email }}</span></p>
						<p class="">No of accounts: <span class="text-info">{{ user.account_set.count }}</span></p>
					</div>
				</div>
				<a href="{% url 'user:profile_edit' %}" class="btn btn-primary btn-block mt-sm-3">Edit Account</a>
			</div>			
		</div>
	</div>
{% endblock %}

user/templates/user/profile_edit.html
{% extends 'user/base.html' %}


{% block head %}
	<title>Edit {{user.username}}'s Profile</title>
{% endblock %}
{% block content %}
	<div class="container" style="position:relative;z-index:2;">
		<form enctype="multipart/form-data" action='.' style="max-width:400px;margin:20px auto auto auto;" method = 'post'>
			{% csrf_token %}
			{{f}}
			{% for field in u_form %}
				<div class="form-group">
					{{field.label_tag}}
					{{ field }}
					<span class="small text-muted text-info">{{ field.help_text }}</span>
				</div>
			{% endfor %}
			<div class="form-group">
				<label for="">Profile Pic:</label>
				<div class="input-group">
					<div class="custom-file">
						<input value="{{user.profilepic.profile.url}}" class="custom-file-input" type="file" id="id_profile" name="profile" accept="image/*">
						<label for="{{p_form.profile.id_for_label}}" class="custom-file-label">Choose File</label>
					</div>
				</div>
			</div>
			<input type="submit" value="Save Changes" class=" mb-3 btn btn-primary btn-block">
		</form>
	</div>
{% endblock %}

user/templates/user/signin.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign In</title>
    <style>
        .container img{
            width:150px;
            height:150px;
            position:absolute;
            border-radius:50%;
            border:5px solid rgba(255,255,255,0.7);
            top:-80px;
            left:calc((100% - 160px)/2);
            background:white;
        }
        p{
            margin:auto;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:1">
       <img src="{% static 'user\images\user4.png' %}" alt="">
        <form action="." method="post" style="max-width:400px;margin:140px auto;padding-top:80px;">
            {% csrf_token %}
            <div class="form-group">
                {{form.username.label_tag}}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{form.password.label_tag}}
                {{ form.password }}
            </div>
            <p class="text-right small"><a href="{% url 'password_reset' %}">Forgot Password</a></p>
            <button type="submit" class="btn btn-dark btn-block mt-2">Sign In</button>
            <p class="text-muted mt-2 text-center small">Need An Account? <a href="{% url 'user:signup' %}">Sign Up</a></p>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $('#id_username').attr('class','form-control');
        $('#id_password').attr('class','form-control');
        
        // Create a function that changes the profile pic when it finds a username being entered in the input field
        let getUserProfilePic = () => {
            $('input[id = id_username]').keyup(function(){
                let username = $(this).val();
                $.ajax({
                    url: "{% url 'user:image_url' %}",
                    data: {
                        'username': username,
                    },
                    dateType: 'json',
                    success: function(data){
                        if(data["image_url"]){
                            $('.container img').attr('src',data["image_url"]);  
                        }
						else{
							$('.container img').attr('src',"{% static 'user/images/user4.png' %}");
						}
                    },
                })
            })
        }
        getUserProfilePic() // Invoke the function
    </script>
{% endblock %}

user/templates/user/signup.html
{% extends 'user/base.html' %}
{% load static %}


{% block head %}
    <title>Sign Up</title>
{% endblock %}
{% block content %}
    <div class="container" style="position:relative;z-index:2;">
        <form action="." style="max-width:400px;margin:60px auto auto auto;" method="post">
           {% csrf_token %}
            <div class="form-group">
               {{ form.username.label_tag }}
               {{form.username}}
                {% for error in form.username.errors %}
                    <p class="text-danger small mt-1">{{ error }}</p>
                {% endfor %}

            </div>
            <div class="form-group">
               {{ form.email.label_tag }}
                {{form.email}}
            </div>
            <div class="form-group">
               {{ form.password1.label_tag }}
                {{form.password1}}
                <p class="text-info small mt-1">Password should be at least 8 characters long.</p>
            </div>
            <div class="form-group">
               {{ form.password2.label_tag }}
                {{form.password2}}
                <p class="text-info small mt-1">Password should be the same as the password entered above.</p>
            </div>
            <button class="btn btn-block btn-dark">Proceed & Continue</button>
            <p class = 'text-muted text-center small mt-2'>Already Have An Account? <a href="{% url 'user:signin' %}">Sign In</a></p>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        $("#id_password1").attr('class','form-control');
        $("#id_password2").attr('class','form-control');
    </script>
{% endblock %}